# -*- coding: utf-8 -*-
"""web_page.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DOdI0UCfqWKmVom2klkrjVIk5UDLUGI
"""

pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

# Specify the URL of the web page you want to import
url = "https://www.geeksforgeeks.org/artificial-intelligence-an-introduction/"

# Send an HTTP GET request to fetch the web page content
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Print the prettified HTML content (optional)
    print(soup.prettify())
else:
    print("Failed to fetch the web page.")

# Find a specific element by tag and class
title_element = soup.find('h1', class_='title-class')
if title_element:
    print("Title:", title_element.text)

# Find all elements of a specific tag
paragraphs = soup.find_all('p')
for paragraph in paragraphs:
    print("Paragraph:", paragraph.text)